### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by yezi2949** [DetectionTeamUCAS/FPN_Tensorflow#10]
Traceback (most recent call last):
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qzhang/Desktop/FPN_Tensorflow-master/tools/train.py", line 187, in <module>
    train()
  File "/home/qzhang/Desktop/FPN_Tensorflow-master/tools/train.py", line 145, in train
    _, global_stepnp = sess.run([train_op, global_step])
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

Caused by op 'get_batch/batch', defined at:
  File "/home/qzhang/Desktop/FPN_Tensorflow-master/tools/train.py", line 187, in <module>
    train()
  File "/home/qzhang/Desktop/FPN_Tensorflow-master/tools/train.py", line 35, in train
    is_training=True)
  File "/home/qzhang/Desktop/FPN_Tensorflow-master/data/io/read_tfrecord.py", line 98, in next_batch
    dynamic_pad=True)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 988, in batch
    name=name)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 762, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py", line 483, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/qzhang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

**Comment by yangxue0827** [comment]
check your data, there must be something wrong with your tfrecord. @yezi2949
