### ISSUE TITLE
多GPU训练报错，CPU训练不报错

### ISSUE THREAD

**Issue by gongyilong** [DetectionTeamUCAS/FPN_Tensorflow#101]
多GPU训练报错如下（ubuntu16.04下）：

OutOfRangeError (see above for traceback): box_index has values outside [0, batch_size)
	 [[Node: tower_0/gradients/tower_0/Fast-RCNN/rois_pooling/ROI_Warping_P2/CROP_AND_RESIZE_grad/CropAndResizeGradImage = CropAndResizeGradImage[T=DT_FLOAT, method="bilinear", _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/gradients/tower_0/Fast-RCNN/rois_pooling/ROI_Warping_P2/MaxPool2D/MaxPool_grad/MaxPoolGrad, tower_0/Fast-RCNN/rois_pooling/ROI_Warping_P2/StopGradient, tower_0/Fast-RCNN/rois_pooling/ROI_Warping_P2/zeros/_6983, tower_0/gradients/tower_0/Fast-RCNN/rois_pooling/ROI_Warping_P2/CROP_AND_RESIZE_grad/Shape)]]

CPU是可以的，但很慢：
************************************************************
2019-09-08 09:50:35: global_step:510  current_step:510
per_cost_time:2.970s
fastrcnn_cls_loss:0.012
fastrcnn_loc_loss:0.000
rpn_cls_loss:0.273
rpn_loc_loss:0.128
total_losses:0.413

************************************************************
2019-09-08 09:51:04: global_step:520  current_step:520
per_cost_time:2.857s
fastrcnn_cls_loss:0.002
fastrcnn_loc_loss:0.000
rpn_cls_loss:0.507
rpn_loc_loss:0.484
total_losses:0.992

请问这是什么问题呢？我把batch_size设置为1，GPU_GROUP = "0,1,2,3"
请问是哪里没有设置对吗？

**Comment by yangxue0827** [comment]
看起来没毛病。

**Comment by balabala7776** [comment]
请问解决了吗？单GPU和CPU我都OK，多GPU是报错了

**Comment by balabala7776** [comment]
with 10479 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1)
2019-12-10 09:38:38.965165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10479 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1)
2019-12-10 09:38:38.966772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10479 MB memory) -> physical GPU (device: 2, name: GeForce GTX 1080 Ti, pci bus id: 0000:84:00.0, compute capability: 6.1)
2019-12-10 09:38:38.968567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10479 MB memory) -> physical GPU (device: 3, name: GeForce GTX 1080 Ti, pci bus id: 0000:88:00.0, compute capability: 6.1)
2019-12-10 09:38:38.970350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 10479 MB memory) -> physical GPU (device: 4, name: GeForce GTX 1080 Ti, pci bus id: 0000:89:00.0, compute capability: 6.1)
2019-12-10 09:38:41.764367: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
WARNING:tensorflow:From multi_gpu_train.py:272: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From multi_gpu_train.py:276: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

WARNING:tensorflow:From /home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-12-10 09:38:48.130353: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key Fast-RCNN/build_fc_layers/fc1/biases/ExponentialMovingAverage not found in checkpoint
2019-12-10 09:38:48.145912: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.145985: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146013: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146034: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146056: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146077: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146096: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146114: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146164: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146216: W tensorflow/core/kernels/queue_base.cc:277] _0_get_batch/input_producer: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146256: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146279: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146304: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146322: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146343: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146443: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
2019-12-10 09:38:48.146476: W tensorflow/core/kernels/queue_base.cc:277] _2_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key Fast-RCNN/build_fc_layers/fc1/biases/ExponentialMovingAverage not found in checkpoint
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Fast-RCNN/build_fc_layers/fc1/biases/ExponentialMovingAverage not found in checkpoint
         [[node save/RestoreV2 (defined at ../libs/networks/build_whole_network.py:547) ]]

Original stack trace for 'save/RestoreV2':
  File "multi_gpu_train.py", line 346, in <module>
    train()
  File "multi_gpu_train.py", line 256, in train
    restorer, restore_ckpt = faster_rcnn.get_restorer()
  File "../libs/networks/build_whole_network.py", line 547, in get_restorer
    restorer = tf.train.Saver()
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1296, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1614, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 678, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multi_gpu_train.py", line 346, in <module>
    train()
  File "multi_gpu_train.py", line 279, in train
    restorer.restore(sess, restore_ckpt)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1302, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key Fast-RCNN/build_fc_layers/fc1/biases/ExponentialMovingAverage not found in checkpoint
         [[node save/RestoreV2 (defined at ../libs/networks/build_whole_network.py:547) ]]

Original stack trace for 'save/RestoreV2':
  File "multi_gpu_train.py", line 346, in <module>
    train()
  File "multi_gpu_train.py", line 256, in train
    restorer, restore_ckpt = faster_rcnn.get_restorer()
  File "../libs/networks/build_whole_network.py", line 547, in get_restorer
    restorer = tf.train.Saver()
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/yuanyq/anaconda3/envs/Tensorflow1.10/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
