### ISSUE TITLE
Not found: ../data/tfrecord; No such file or directory

### ISSUE THREAD

**Issue by HUI11126** [DetectionTeamUCAS/FPN_Tensorflow#147]
2020-12-29 11:04:21.313687: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at matching_files_op.cc:49 : Not found: ../data/tfrecord; No such file or directory
2020-12-29 11:04:21.313951: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at matching_files_op.cc:49 : Not found: ../data/tfrecord; No such file or directory
Traceback (most recent call last):
  File "/home/shaohui/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/shaohui/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/shaohui/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: ../data/tfrecord; No such file or directory
	 [[{{node get_batch/matching_filenames/MatchingFiles}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shaohui/FPC_Defect_with_FPN/tools/train.py", line 194, in <module>
    train()
  File "/home/shaohui/FPC_Defect_with_FPN/tools/train.py", line 131, in train
    sess.run(init_op)
  File "/home/shaohui/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/shaohui/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/shaohui/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/shaohui/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: ../data/tfrecord; No such file or directory
	 [[node get_batch/matching_filenames/MatchingFiles (defined at /FPC_Defect_with_FPN/data/io/read_tfrecord.py:86) ]]

Original stack trace for 'get_batch/matching_filenames/MatchingFiles':
  File "/FPC_Defect_with_FPN/tools/train.py", line 194, in <module>
    train()
  File "/FPC_Defect_with_FPN/tools/train.py", line 34, in train
    is_training=True)
  File "/FPC_Defect_with_FPN/data/io/read_tfrecord.py", line 86, in next_batch
    filename_tensorlist = tf.train.match_filenames_once(pattern)
  File "/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/training/input.py", line 77, in match_filenames_once
    name=name, initial_value=io_ops.matching_files(pattern),
  File "/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 464, in matching_files
    "MatchingFiles", pattern=pattern, name=name)
  File "/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

有人遇到过这个问题吗？找不到路径

**Comment by yangxue0827** [comment]
cd $PATH_ROOT/tools  (important!)
python train.py

**Comment by HUI11126** [comment]
在data目录下新建一个tfrecord文件夹解决了
