### ISSUE TITLE
在训练FPN_MobileNetv2的时候出现Tensor objects are not iterable when eager execution is not enabled

### ISSUE THREAD

**Issue by HelloWorld19930113** [DetectionTeamUCAS/FPN_Tensorflow#18]
Traceback (most recent call last):
  File "/home/litao/Algorithm/FPN_Tensorflow-master/tools/train.py", line 188, in <module>
    train()
  File "/home/litao/Algorithm/FPN_Tensorflow-master/tools/train.py", line 48, in train
    gtboxes_batch=gtboxes_and_label)
  File "../libs/networks/build_whole_network.py", line 390, in build_whole_detection_network
    for level_name, p in zip(cfgs.LEVLES, P_list):
  File "/home/litao/anaconda2/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 431, in __iter__
    "Tensor objects are not iterable when eager execution is not "
**TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.**

**Comment by yangxue0827** [comment]
MobileNetv2我没有改，暂不支持。 @HelloWorld19930113
