### ISSUE TITLE
训练自己的数据出现的问题！

### ISSUE THREAD

**Issue by lo-pan** [DetectionTeamUCAS/FPN_Tensorflow#37]
楼主你好，我用你的程序训练数据。开始我拿pascal_voc的前几十张图片测试了一下，是可以训练的。但是修改了代码之后用我自己的数据训练，格式也是pascal voc格式，出现下面这个问题

> Traceback (most recent call last):
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 194, in <module>
    train()
  File "train.py", line 174, in train
    _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

Caused by op 'get_batch/batch', defined at:
  File "train.py", line 194, in <module>
    train()
  File "train.py", line 34, in train
    is_training=True)
  File "../data/io/read_tfrecord.py", line 98, in next_batch
    dynamic_pad=True)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 988, in batch
    name=name)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 762, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py", line 476, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3480, in queue_dequeue_many_v2
    component_types=component_types, timeout_ms=timeout_ms, name=name)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/home/amax/panzhihao/FPN_Tensorflow/venv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

我查了一下，说是数据大小不一致，但是我的数据以前在caffe上的程序跑过，并没有问题，请楼主指教一下，谢谢！

**Comment by yangxue0827** [comment]
tfrecord制作有问题，再检查一下吧 @lo-pan

**Comment by lo-pan** [comment]
楼主，我想在你的代码基础上增加卷积层数，请问是在libs/networks/build_whole/network.py上进行修改吗？

**Comment by yangxue0827** [comment]
或者resnet.py @lo-pan

**Comment by lo-pan** [comment]
好的，谢谢楼主

**Comment by WangGangUCAS** [comment]
你怎么解决的？？？ @lo-pan
