### ISSUE TITLE
采用mobilenetv2报错

### ISSUE THREAD

**Issue by summerrr** [DetectionTeamUCAS/FPN_Tensorflow#47]
我在cfgs.py中设了mobilenetv2作为特征提取网络，但是报错，请问你知道是什么原因吗
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    train()
  File "train.py", line 48, in train
    gtboxes_batch=gtboxes_and_label)
  File "../libs/networks/build_whole_network.py", line 383, in build_whole_detection_network
    for level_name, p in zip(cfgs.LEVLES, P_list):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 431, in __iter__
    "Tensor objects are not iterable when eager execution is not "
TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.

**Comment by yangxue0827** [comment]
这个代码我没有加mobilenet的FPN代码 @summerrr
