### ISSUE TITLE
训练的时候处错误

### ISSUE THREAD

**Issue by memeda2232** [DetectionTeamUCAS/FPN_Tensorflow#53]
2019-03-11 22:00:29.135446: W tensorflow/core/framework/op_kernel.cc:1306] Invalid argument: ValueError: attempt to get argmax of an empty sequence
Traceback (most recent call last):

  File "/home/zysz1/python3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "../libs/detection_oprations/anchor_target_layer_without_boxweight.py", line 53, in anchor_target_layer
    argmax_overlaps = overlaps.argmax(axis=1)

ValueError: attempt to get argmax of an empty sequence
训练的时候总是这个错误，请问大佬有碰到吗

**Comment by tienhoang1094** [comment]
how u solve it
