### ISSUE TITLE
使用自己的训练集训练正常，但测试出错

### ISSUE THREAD

**Issue by zxmfgky** [DetectionTeamUCAS/FPN_Tensorflow#6]
________________________________________
model restore from : /raid/cc/extend/FPN_Tensorflow/output/trained_weights/FPN_Res101_20181201/voc_120001model.ckpt
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:06:00.0
Total memory: 11.93GiB
Free memory: 11.81GiB
2018-12-05 17:04:54.307583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-12-05 17:04:54.307590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-12-05 17:04:54.307597: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:06:00.0)
restore model
2018-12-05 17:04:58.326784: I tensorflow/core/kernels/logging_ops.cc:79] SHAPE4***[0]
2018-12-05 17:04:58.326785: I tensorflow/core/kernels/logging_ops.cc:79] SHAPE3***[0]
2018-12-05 17:04:58.326818: I tensorflow/core/kernels/logging_ops.cc:79] SHAPE2***[555]
2018-12-05 17:04:58.326790: I tensorflow/core/kernels/logging_ops.cc:79] SHAPE5***[0]
/raid/cc/extend/FPN_Tensorflow/data/demos/img_6.jpg image cost 2.74012804031s:[>>>>>                                   ]13%	1/82018-12-05 17:04:59.071122: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
2018-12-05 17:04:59.071244: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](assign_levels/Equal)]]
2018-12-05 17:04:59.071258: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](assign_levels/Equal)]]
2018-12-05 17:04:59.071267: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](assign_levels/Equal)]]
2018-12-05 17:04:59.071294: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](assign_levels/Equal)]]
2018-12-05 17:04:59.071301: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](assign_levels/Equal)]]
2018-12-05 17:04:59.071300: W tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](assign_levels/Equal)]]
Traceback (most recent call last):
  File "/home/cc/extend/FPN_Tensorflow/tools/test.py", line 138, in <module>
    inference_save_path=args.save_dir)
  File "/home/cc/extend/FPN_Tensorflow/tools/test.py", line 105, in test
    detect(det_net=faster_rcnn, inference_save_path=inference_save_path, real_test_imgname_list=test_imgname_list)
  File "/home/cc/extend/FPN_Tensorflow/tools/test.py", line 60, in detect
    feed_dict={img_plac: raw_img[:, :, ::-1]}  # cv is BGR. But need RGB
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](assign_levels/Equal)]]
	 [[Node: postprocess_fastrcnn/concat_2/_1287 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_5171_postprocess_fastrcnn/concat_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'assign_levels/Where', defined at:
  File "/home/cc/extend/FPN_Tensorflow/tools/test.py", line 138, in <module>
    inference_save_path=args.save_dir)
  File "/home/cc/extend/FPN_Tensorflow/tools/test.py", line 105, in test
    detect(det_net=faster_rcnn, inference_save_path=inference_save_path, real_test_imgname_list=test_imgname_list)
  File "/home/cc/extend/FPN_Tensorflow/tools/test.py", line 35, in detect
    gtboxes_batch=None)
  File "/home/cc/extend/FPN_Tensorflow/libs/networks/build_whole_network.py", line 493, in build_whole_detection_network
    rois_list = self.assign_levels(all_rois=rois)  # rois_list: [P2_rois, P3_rois, P4_rois, P5_rois]
  File "/home/cc/extend/FPN_Tensorflow/libs/networks/build_whole_network.py", line 253, in assign_levels
    bbox_targets=bbox_targets)
  File "/home/cc/extend/FPN_Tensorflow/libs/networks/build_whole_network.py", line 218, in get_rois
    level_i_indices = tf.reshape(tf.where(tf.equal(levels, level_i)), [-1])
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2365, in where
    return gen_array_ops.where(input=condition, name=name)
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4053, in where
    result = _op_def_lib.apply_op("Where", input=input, name=name)
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/cc/miniconda3/envs/chinese-ocr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices.  temp_storage_bytes: 1, status: invalid configuration argument
	 [[Node: assign_levels/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](assign_levels/Equal)]]
	 [[Node: postprocess_fastrcnn/concat_2/_1287 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_5171_postprocess_fastrcnn/concat_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Process finished with exit code 1

我使用的是cuda8.0，还请作者赐教！

**Comment by yangxue0827** [comment]
我看你测试了13%，那测试成功的图有效果吗？你可以单独运行一下报错的那个图，可能那张图片有问题。

**Comment by zxmfgky** [comment]
好像不是图片的问题，我单独测试每一张图都是可以的，效果也很正常；而且每次测试的第一张图都能运行，从第二张或是第三张开始就报错。

**Comment by yangxue0827** [comment]
你用一下inference.py吧 @zxmfgky

**Comment by zxmfgky** [comment]
还是报一样的错

**Comment by yangxue0827** [comment]
在assign level 阶段可能由于被分配为空，然后空的roi去crop featuremap的时候低版本tensorflow是会出问题的。 @zxmfgky 
怎么解决我现在正在想办法。

**Comment by yangxue0827** [comment]
已经改好了cuda版本的问题，在cuda8环境下的测试结果和cuda9基本一致。 @zxmfgky @heiyuxiaokai

**Comment by yangxue0827** [comment]
还是有问题，有时候可以成功，有时候会保存，看运气 @zxmfgky @heiyuxiaokai

**Comment by yangxue0827** [comment]
你们试一下，现在可以了吗？ @zxmfgky @heiyuxiaokai

**Comment by heiyuxiaokai** [comment]
可以了，训练的loss问题是因为转换数据的框有问题

**Comment by yangxue0827** [comment]
我测试了一下mAP，基本是和cuda9一致的 @heiyuxiaokai
