### ISSUE TITLE
迭代时在某一个步数就卡着不动了 每次卡的步数也不同  也不报错

### ISSUE THREAD

**Issue by windtaker** [DetectionTeamUCAS/FPN_Tensorflow#68]

**Comment by windtaker** [comment]
2019-05-08 10:16:44: step6084    image_name:b'00081.jpg' |	
                              rpn_loc_loss:0.030485596507787704 |	 rpn_cla_loss:0.02782752551138401 |	 rpn_total_loss:0.058313123881816864 |
                              fast_rcnn_loc_loss:0.22095617651939392 |	 fast_rcnn_cla_loss:0.28429150581359863 |	 fast_rcnn_total_loss:0.5052477121353149 |
                              total_loss:1.1176228523254395 |	 per_cost_time:4.538814306259155s
 2019-05-08 10:17:35: step6094    image_name:b'00091.jpg' |	
                              rpn_loc_loss:0.004804039839655161 |	 rpn_cla_loss:0.0006960160681046546 |	 rpn_total_loss:0.0055000558495521545 |
                              fast_rcnn_loc_loss:0.10446720570325851 |	 fast_rcnn_cla_loss:0.11471012234687805 |	 fast_rcnn_total_loss:0.21917733550071716 |
                              total_loss:0.7787293791770935 |	 per_cost_time:1.9671297073364258s
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x00000236A424F150>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 251, in <genexpr>
    if all(array.shape == shape for array in args):
SystemError: error return without exception set
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x00000236A424F150>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 251, in <genexpr>
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x00000236A401F8E0>
Exception ignored in: <generator object ScalarFormatter._compute_offset.<locals>.<genexpr> at 0x00000237146EF0A0>
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x00000237146EF150>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 251, in <genexpr>
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x00000237146EF308>
  File "D:\anaconda\lib\site-packages\matplotlib\ticker.py", line 696, in <genexpr>
  File "D:\anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 251, in <genexpr>
    if all(array.shape == shape for array in args):
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x00000237146EF360>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 251, in <genexpr>
SystemError: error return without exception set
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 251, in <genexpr>
    if all(array.shape == shape for array in args):
    if all(array.shape == shape for array in args):
SystemError: error return without exception set
SystemError: error return without exception set
    if all(array.shape == shape for array in args):
SystemError: error return without exception set
    if all(array.shape == shape for array in args):
SystemError: error return without exception set
Exception ignored in: <generator object ScalarFormatter._compute_offset.<locals>.<genexpr> at 0x00000237146EF410>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\ticker.py", line 696, in <genexpr>
Exception ignored in: <generator object ScalarFormatter._compute_offset.<locals>.<genexpr> at 0x00000237146EF360>
Traceback (most recent call last):
    if abs_min // 10 ** oom != abs_max // 10 ** oom)
SystemError: error return without exception set
  File "D:\anaconda\lib\site-packages\matplotlib\ticker.py", line 696, in <genexpr>
Exception ignored in: <generator object ScalarFormatter._compute_offset.<locals>.<genexpr> at 0x00000237146EF570>
Exception ignored in: <generator object _draw_list_compositing_images.<locals>.<genexpr> at 0x00000237146EF6D0>
Traceback (most recent call last):
    if abs_min // 10 ** oom != abs_max // 10 ** oom)
SystemError: error return without exception set
    if abs_min // 10 ** oom != abs_max // 10 ** oom)
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\ticker.py", line 696, in <genexpr>
  File "D:\anaconda\lib\site-packages\matplotlib\image.py", line 133, in <genexpr>
SystemError: error return without exception set
    has_images = any(isinstance(x, _ImageBase) for x in artists)
SystemError: error return without exception set
    if abs_min // 10 ** oom != abs_max // 10 ** oom)
SystemError: error return without exception set
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x00000237146EF830>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 251, in <genexpr>
Exception ignored in: <generator object broadcast_arrays.<locals>.<genexpr> at 0x00000237146EFA98>
    if all(array.shape == shape for array in args):
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\numpy\lib\stride_tricks.py", line 251, in <genexpr>
SystemError: error return without exception set
    if all(array.shape == shape for array in args):
SystemError: error return without exception set
Exception ignored in: <generator object _draw_list_compositing_images.<locals>.<genexpr> at 0x00000237146EF938>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\image.py", line 133, in <genexpr>
    has_images = any(isinstance(x, _ImageBase) for x in artists)
SystemError: error return without exception set
Exception ignored in: <generator object _draw_list_compositing_images.<locals>.<genexpr> at 0x00000237146EFFC0>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\image.py", line 133, in <genexpr>
    has_images = any(isinstance(x, _ImageBase) for x in artists)
SystemError: error return without exception set
Exception ignored in: <generator object _draw_list_compositing_images.<locals>.<genexpr> at 0x00000237146EFFC0>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\image.py", line 133, in <genexpr>
    has_images = any(isinstance(x, _ImageBase) for x in artists)
SystemError: error return without exception set
Exception ignored in: <generator object _draw_list_compositing_images.<locals>.<genexpr> at 0x00000237146EFFC0>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\image.py", line 133, in <genexpr>
    has_images = any(isinstance(x, _ImageBase) for x in artists)
SystemError: error return without exception set
Exception ignored in: <generator object _draw_list_compositing_images.<locals>.<genexpr> at 0x00000237146EFF68>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\image.py", line 133, in <genexpr>
    has_images = any(isinstance(x, _ImageBase) for x in artists)
SystemError: error return without exception set
Exception ignored in: <generator object _draw_list_compositing_images.<locals>.<genexpr> at 0x00000237146EFF68>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\image.py", line 133, in <genexpr>
    has_images = any(isinstance(x, _ImageBase) for x in artists)
SystemError: error return without exception set
Exception ignored in: <generator object _draw_list_compositing_images.<locals>.<genexpr> at 0x00000237146EFF68>
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\matplotlib\image.py", line 133, in <genexpr>
    has_images = any(isinstance(x, _ImageBase) for x in artists)
SystemError: error return without exception set
 2019-05-08 10:18:53: step6114    image_name:b'00111.jpg' |	
                              rpn_loc_loss:0.013263504020869732 |	 rpn_cla_loss:0.002877325750887394 |	 rpn_total_loss:0.016140829771757126 |
                              fast_rcnn_loc_loss:0.0937037244439125 |	 fast_rcnn_cla_loss:0.11611999571323395 |	 fast_rcnn_total_loss:0.20982372760772705 |
                              total_loss:0.779998779296875 |	 per_cost_time:2.0815885066986084s
 2019-05-08 10:19:35: step6124    image_name:b'00121.jpg' |	
                              rpn_loc_loss:0.005503425374627113 |	 rpn_cla_loss:0.01271093264222145 |	 rpn_total_loss:0.018214358016848564 |
                              fast_rcnn_loc_loss:0.13997149467468262 |	 fast_rcnn_cla_loss:0.11881488561630249 |	 fast_rcnn_total_loss:0.2587863802909851 |
                              total_loss:0.8310241103172302 |	 per_cost_time:2.5939548015594482s

**Comment by windtaker** [comment]
上面是debug出现的情况  仍然能迭代  但是到一定的步数就会卡着不动

**Comment by windtaker** [comment]
随后就停止了
 2019-05-08 10:28:53: step6254    image_name:b'00254.jpg' |	
                              rpn_loc_loss:0.0075707570649683475 |	 rpn_cla_loss:0.00027748101274482906 |	 rpn_total_loss:0.00784823764115572 |
                              fast_rcnn_loc_loss:0.08869355171918869 |	 fast_rcnn_cla_loss:0.052132509648799896 |	 fast_rcnn_total_loss:0.1408260613679886 |
                              total_loss:0.7025763392448425 |	 per_cost_time:2.0956292152404785s
 2019-05-08 10:29:33: step6264    image_name:b'00264.jpg' |	
                              rpn_loc_loss:0.0038451035507023335 |	 rpn_cla_loss:0.0021091962698847055 |	 rpn_total_loss:0.005954300053417683 |
                              fast_rcnn_loc_loss:0.029192190617322922 |	 fast_rcnn_cla_loss:0.04998209327459335 |	 fast_rcnn_total_loss:0.07917428016662598 |
                              total_loss:0.6390182375907898 |	 per_cost_time:1.2813522815704346s
 2019-05-08 10:30:04: step6274    image_name:b'00274.jpg' |	
                              rpn_loc_loss:0.00819952879101038 |	 rpn_cla_loss:0.0019030855037271976 |	 rpn_total_loss:0.010102614760398865 |
                              fast_rcnn_loc_loss:0.07272785902023315 |	 fast_rcnn_cla_loss:0.07715249061584473 |	 fast_rcnn_total_loss:0.14988034963607788 |
                              total_loss:0.7138627767562866 |	 per_cost_time:2.062661647796631s
2019-05-08 10:30:56.656572: E tensorflow/stream_executor/cuda/cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-05-08 10:30:56.656982: E tensorflow/stream_executor/cuda/cuda_timer.cc:55] Internal: error destroying CUDA event in context 00000236A57ED290: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-05-08 10:30:56.657422: E tensorflow/stream_executor/cuda/cuda_timer.cc:60] Internal: error destroying CUDA event in context 00000236A57ED290: CUDA_ERROR_LAUNCH_TIMEOUT: the launch timed out and was terminated
2019-05-08 10:30:56.657882: F tensorflow/stream_executor/cuda/cuda_dnn.cc:211] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.

Process finished with exit code -1073740791 (0xC0000409)

**Comment by windtaker** [comment]
@yangxue0827 @yangJirui @toubasi

**Comment by VerbF** [comment]
楼主解决了吗，我也遇到这个问题。

**Comment by windtaker** [comment]
> 楼主解决了吗，我也遇到这个问题。

我原先的环境是 windows + python3.6+cuda9 
后来将环境换为ubuntu + python2.7 + cuda8就好了
