### ISSUE TITLE
TypeError: Expected string passed to parameter 'pattern' of op 'MatchingFiles' 

### ISSUE THREAD

**Issue by Dalal1983** [DetectionTeamUCAS/FPN_Tensorflow#70]
Hi
Please could you help me, I got this error when I tried to run **multi_gpu_train.py**.
**I use windows 10, and Cuda10** 

D:\Master China project\Superveser2\Projects\Faster\FPN_Tensorflow-master
WARNING:tensorflow:From multi_gpu_train.py:104: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
WARNING:tensorflow:From C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
tfrecord path is --> D:\Master China project\Superveser2\Projects\Faster\FPN_Tensorflow-master\data\tfrecord\vhr_train*
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 511, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 501, in make_tensor_proto
    (dtype, nparray.dtype, values))
TypeError: Incompatible types: <dtype: 'string'> vs. object. Value is ../data/tfrecord\vhr_train*

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multi_gpu_train.py", line 346, in <module>
    train()
  File "multi_gpu_train.py", line 120, in train
    is_training=True)
  File "..\data\io\read_tfrecord_multi_gpu.py", line 92, in next_batch
    filename_tensorlist = tf.train.match_filenames_once(pattern)
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\training\input.py", line 77, in match_filenames_once
    name=name, initial_value=io_ops.matching_files(pattern),
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 454, in matching_files
    "MatchingFiles", pattern=pattern, name=name)
  File "C:\Users\lenovo\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 520, in _apply_op_helper
    repr(values), type(values).__name__))
TypeError: Expected string passed to parameter 'pattern' of op 'MatchingFiles', got '../data/tfrecord\\vhr_train*' of type 'str' instead.

**Comment by yangxue0827** [comment]
wrong tfrecord path @Dalal1983

**Comment by Dalal1983** [comment]
@yangxue0827 thank you.
but I do not get this error when I run train.py with read_tfrecod.py.
also, I wrote the whole path but I got the same.
