### ISSUE TITLE
运行train.py时报错，

### ISSUE THREAD

**Issue by frank-chan-ck** [DetectionTeamUCAS/FPN_Tensorflow#86]
运行python convert_data_to_tfrecord.py --VOC_dir='/home/user/Documents/FPN/VOCdevkit/VOCdevkit_train/' --xml_dir='Annotations' --image_dir='JPEGImages' --save_name='train' --img_format='.jpg' --dataset='my_own' 
后生成了my_own_train.tfrecord，确认已经生成该文件，大小跟pascal_train.tfrecord一样。然后运行train.py，出现以下错误：
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1024,8] rhs shape= [1024,84]
	 [[Node: save/Assign_14 = Assign[T=DT_FLOAT, _class=["loc:@Fast-RCNN/reg_fc/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Fast-RCNN/reg_fc/weights, save/RestoreV2/_33)]]
	 [[Node: save/RestoreV2/_676 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_678_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:336)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 188, in <module>
    train()
  File "train.py", line 133, in train
    restorer.restore(sess, restore_ckpt)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1752, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1024,8] rhs shape= [1024,84]
	 [[Node: save/Assign_14 = Assign[T=DT_FLOAT, _class=["loc:@Fast-RCNN/reg_fc/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Fast-RCNN/reg_fc/weights, save/RestoreV2/_33)]]
	 [[Node: save/RestoreV2/_676 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_678_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:336)]]

Caused by op 'save/Assign_14', defined at:
  File "train.py", line 188, in <module>
    train()
  File "train.py", line 124, in train
    restorer, restore_ckpt = faster_rcnn.get_restorer()
  File "../libs/networks/build_whole_network.py", line 547, in get_restorer
    restorer = tf.train.Saver()
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1284, in __init__
    self.build()
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1333, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 781, in _build_internal
    restore_sequentially, reshape)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 422, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 113, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 219, in assign
    validate_shape=validate_shape)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1024,8] rhs shape= [1024,84]
	 [[Node: save/Assign_14 = Assign[T=DT_FLOAT, _class=["loc:@Fast-RCNN/reg_fc/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Fast-RCNN/reg_fc/weights, save/RestoreV2/_33)]]
	 [[Node: save/RestoreV2/_676 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_678_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:336)]]

**### 请问这是什么问题，怎么解决？**
另外，我标注数据集时只标注了一个person类型，对应的cfgs.py中修改了以下变量：
IMG_SHORT_SIDE_LEN = 288  
IMG_MAX_LENGTH = 352  
CLASS_NUM = 1
DATASET_NAME = 'my_own'
test_annotate_path = ROOT_PATH +'VOCdevkit/VOCdevkit_test/Annotations'

**Comment by yangxue0827** [comment]
你是不是加载了我训练好的测试模型，没有加载预训练模型？ @LowWisdom

**Comment by frank-chan-ck** [comment]
> 你是不是加载了我训练好的测试模型，没有加载预训练模型？ @LowWisdom

谢谢提醒，已经在build_whole_network.py中的get_restorer函数中屏蔽checkpoint_path = tf.train.latest_checkpoint(os.path.join(cfgs.TRAINED_CKPT, cfgs.VERSION))，换成checkpoint_path = None
### **重新运行train.py后成功出现：restore from pretrained_weighs in IMAGE_NET，但是又出现新错误：**
: 'FigureCanvasBase' object has no attribute 'tostring_argb'
Traceback (most recent call last):

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/ops.py", line 101, in _render_image
    image = figure.to_array(fig)

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/figure.py", line 90, in to_array
    img = np.frombuffer(fig.canvas.tostring_argb(), dtype=np.uint8)

AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_argb'


2019-07-07 17:06:35.415478: W tensorflow/core/kernels/queue_base.cc:277] _0_get_batch/input_producer: Skipping cancelled enqueue attempt with queue not closed
2019-07-07 17:06:35.415619: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_argb'
Traceback (most recent call last):

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/ops.py", line 101, in _render_image
    image = figure.to_array(fig)

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/figure.py", line 90, in to_array
    img = np.frombuffer(fig.canvas.tostring_argb(), dtype=np.uint8)

AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_argb'


	 [[Node: Layer2/C2_heat/Plot = PyFunc[Tin=[DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Squeeze/_1157)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 188, in <module>
    train()
  File "train.py", line 168, in train
    _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_argb'
Traceback (most recent call last):

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/ops.py", line 101, in _render_image
    image = figure.to_array(fig)

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/figure.py", line 90, in to_array
    img = np.frombuffer(fig.canvas.tostring_argb(), dtype=np.uint8)

AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_argb'


	 [[Node: Layer2/C2_heat/Plot = PyFunc[Tin=[DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Squeeze/_1157)]]

Caused by op 'Layer2/C2_heat/Plot', defined at:
  File "train.py", line 188, in <module>
    train()
  File "train.py", line 48, in train
    gtboxes_batch=gtboxes_and_label)
  File "../libs/networks/build_whole_network.py", line 382, in build_whole_detection_network
    P_list = self.build_base_network(input_img_batch)  # [P2, P3, P4, P5, P6]
  File "../libs/networks/build_whole_network.py", line 34, in build_base_network
    return resnet.resnet_base(input_img_batch, scope_name=self.base_network_name, is_training=self.is_training)
  File "../libs/networks/resnet.py", line 132, in resnet_base
    add_heatmap(C2, name='Layer2/C2_heat')
  File "../libs/networks/resnet.py", line 88, in add_heatmap
    tfp.summary.plot(name, figure_attention, [heatmap])
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/summary.py", line 45, in plot
    im = ops.plot(plot_func, in_tensors, **kwargs)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/ops.py", line 114, in plot
    name=name)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 384, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 227, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 128, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_argb'
Traceback (most recent call last):

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 158, in __call__
    ret = func(*args)

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/ops.py", line 101, in _render_image
    image = figure.to_array(fig)

  File "/home/user/anaconda3/envs/CKtf1/lib/python3.6/site-packages/tfplot/figure.py", line 90, in to_array
    img = np.frombuffer(fig.canvas.tostring_argb(), dtype=np.uint8)

AttributeError: 'FigureCanvasBase' object has no attribute 'tostring_argb'


	 [[Node: Layer2/C2_heat/Plot = PyFunc[Tin=[DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](Squeeze/_1157)]]

**Comment by frank-chan-ck** [comment]
> 你是不是加载了我训练好的测试模型，没有加载预训练模型？ @LowWisdom

我的tf 装的是1.9，会是这个原因么？

**Comment by yangxue0827** [comment]
tfpolt安装0.2.0版本的 @LowWisdom

**Comment by frank-chan-ck** [comment]
> tfpolt安装0.2.0版本的 @LowWisdom

非常感谢版主的指导！tfpolt版本已换，还是一样的错误。我的软件环境：linux 16.04、 cuda 9.0 、cudnn 7.1.3,tensorflow 1.9.0, python 3.6。还有哪里不对的？

**Comment by yangxue0827** [comment]
把关于tfpolt相关的代码屏蔽一下，看是不是这个模块的问题 @LowWisdom

**Comment by frank-chan-ck** [comment]
> 把关于tfpolt相关的代码屏蔽一下，看是不是这个模块的问题 @LowWisdom

感谢您的建议！我再试试看。另外我想请问一下，我怎么确认生成的.tfrecord文件没有问题？会不会因为生成的这个文件有问题而导致给系统输入的img不对？我后来用一段小程序测试过tostring_argb这个属性，是可用的。我也确认过tfplot的版本为0.2.0。

**Comment by frank-chan-ck** [comment]
> 把关于tfpolt相关的代码屏蔽一下，看是不是这个模块的问题 @LowWisdom

出错信息来自以下程序段：
                    if step % cfgs.SMRY_ITER == 0:
                        _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
                        summary_writer.add_summary(summary_str, global_stepnp)
                        summary_writer.flush()
运行sess.run就出现以上错误，这段程序是为后面可视化过程参数用的，对我训练模型应该影响不大哈？

**Comment by frank-chan-ck** [comment]
> 把关于tfpolt相关的代码屏蔽一下，看是不是这个模块的问题 @LowWisdom

屏蔽以上代码后可以开始训练了，但是过了500轮之后，出现新问题：
File "../libs/detection_oprations/proposal_target_layer.py", line 37, in proposal_target_layer
    rois_per_image, cfgs.CLASS_NUM+1)

  File "../libs/detection_oprations/proposal_target_layer.py", line 148, in _sample_rois
    _get_bbox_regression_labels(bbox_target_data, num_classes)

  File "../libs/detection_oprations/proposal_target_layer.py", line 68, in _get_bbox_regression_labels
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]

ValueError: could not broadcast input array from shape (4) into shape (0)

出现该错误后在proposal_target_layer.py中加入打印行，以上是出错之前的bbox_target_data和clss两个变量的值。
bbox_target_data [[ 2.         -0.6903479   0.16995145 -2.3610926  -0.13599603]
 [ 2.          1.2484696   1.1620762  -2.138445   -0.93094105]
 [ 2.          2.1456075  -0.41808394  2.181404    1.170656  ]
 ...
 [ 0.          2.6663218   1.4620783  -0.7989745  -4.1196203 ]
 [ 0.          5.8787675   1.5966473   1.3476636   1.071497  ]
 [ 0.         13.34938    -3.221199    2.870502   -0.49611065]]
clss: [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
训练之前我修改了以下地方的参数：
我的数据集中只有一类person
cfg.py中修改了：
GPU_GROUP = "0,1,2,3"
DATASET_NAME = 'my_own'
IMG_SHORT_SIDE_LEN = 288 
IMG_MAX_LENGTH = 352
CLASS_NUM = 1
label_dict.py中添加了：
elif cfgs.DATASET_NAME == 'my_own':
    NAME_LABEL_MAP = {
        'back_ground': 0,
        'person': 1        
    }
修改readtf_record.py中：
if dataset_name not in ['my_own', 'ship', 'spacenet', 'pascal', 'coco']:
修改build_whole_network.py中的get_restorer函数
checkpoint_path = None

这种设置怎么会在训练过程中导致出现第2类label的出现？请问问题在哪儿？望交大校友指点一二。

**Comment by yangxue0827** [comment]
你debug一下转换tfrecord的程序吧，估计产生了2的标签 @LowWisdom

**Comment by frank-chan-ck** [comment]
> 你debug一下转换tfrecord的程序吧，估计产生了2的标签 @LowWisdom

非常感谢，问题已经解决，训练80000轮后检测效果就很赞！
